site_name: Григорий GYMович
site_description: Всякие гайды, идеи, находки, и рецепты
site_author: Grigorii Based
site_url: https://docs.grygoriybased.ru/

copyright: Copyright &copy; 2024 <a href="https://t.me/GrigoriyBased">Григорий Базович</a>.

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/mephistiks

markdown_extensions:
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

repo_url: https://github.com/mephistiks/my-wiki
repo_name: mephistiks/my-wiki

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.indexes
  language: ru
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Тёмная тема
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Светлая тема
    # primary: blue grey

plugins:
    - search
    - blog
    - autorefs

nav: 
  - "Главная": index.md

  - "Гойда": 
    - "Вэб":
      - web/index.md
      - "Виртуальное окружение и зависимости": web/venv_pip.md
      - "Конкурентное программирование": web/parallel.md
      - "Асинхронное программирование": web/async.md
    - "Обзоры технологий":
      - review/index.md
      - "IDE": review/ide.md
      - "Работа с докером": review/docker.md
    - "Рецепты":
      - recipes/index.md
      - "Питон в контейнере": recipes/docker-python.md 

  - "Who am я?": about.md
  # - "Блог":
  #   - "Посты": blog.md



# https://chat.openai.com/c/32f7f795-427c-4ecf-90fe-039385d94e1c
